### ISSUE TITLE
Oauth2 request failed

### ISSUE THREAD

**Issue by rafi16jan** [beaufortfrancois/wallpapers-plus-chrome-app#1]
Hello maybe I'm the only one reporting this issue hehe... I find this app is great since I use the opensource chromium os one with no built-in wallpapers to set
![screenshot 2015-05-22 at 14 22 15](https://cloud.githubusercontent.com/assets/7939687/7765936/0b0bccca-008e-11e5-9f05-7ef872ddb8a9.png)

**Comment by beaufortfrancois** [comment]
Thank you Farrell for reporting this.
I've recently played with the app and updated badly server side config. This should be solved now.
Please reopen if that's not the case ;)
